# символ экономики. будет использоваться во всем форматировании цен
currency-symbol: '¤'

# время в секундах, через сколько предмет удалится с аукциона
lifetime:
  # активный предмет, время до истечения
  sell: 43200 # 12 * 60 * 60
  # истекший предмет, время до удаления
  unsold: 604800 # 7 * 24 * 60 * 60

# ограничения по ценам на предметы (за штуку)
price:
  # минимальная цена
  min: 1
  # максимальная цена
  max: 1000000000

# ограничение времени предмета на ставках (секунды)
bids-time:
  # сколько минимально может быть предмет на ставках
  min: 300
  # сколько максимально может быть предмет на ставках
  max: 86400
  # значение, если игрок не указал время
  default: 86400

# ограничение на шаг. если шаг больше чем [цена] * [значение ниже], то игрок не сможет выставить предмет
bids-step-percent: 0.1

# если /ah sell auto не найдет предмет из руки на аукционе,
# то возьмет цену отсюда. (Цена за единицу товара)
default-auto-price: 500

# запрещает выставлять на аукцион шалкера с предметами
sell-only-empty-shulkers: true