# Конфигурация основной базы данных.
database:
  # Тут указываете ту базу данных, которую хотите
  # Варианты:
  # - MySQL
  # - SQLite
  type: SQLite

  # MySQL база данных.
  # Если у вас порт не 3306, то указывайте host: "[host]:[port]".
  global:
    host: localhost
    user: root
    password: ""
    database: "lite_auction"

  # SQLite база данных.
  # Указываете файл с базой данных. Если его нет - создастся автоматически.
  local:
    name: "database.db"

# Конфигурация обмена данными.
communication:
  # Тут указываете ту базу данных, которую хотите
  # Варианты:
  # - Redis
  # - RabbitMQ
  # - Nats
  # - WebSocket
  # - Local (без подключений)
  type: Local

  # Тут указываете настройки для Redis, RabbitMQ, Nats и WebSocket в зависимости от выбора выше.
  # Channel - префикс каналов, всего каналов 4 ([channel]_msg, [channel]_hover, [channel]_sound, [channel]_update).
  redis:
    host: localhost
    port: 6379
    password: ""
    channel: "auction"

  rabbitmq:
    host: localhost
    port: 5672
    vhost: "/"
    user: "root"
    password: ""
    channel: "auction"

  nats:
    host:
      - localhost
    user: "root"
    password: ""
    channel: "auction"

  websocket:
    host: localhost
    port: 8080
    password: ""
    channel: "auction"

# Отвечает за то, что сервер каждую 1 секунду будет обновлять лоты.
# А именно делать лоты истекшими и удалять просроченные лоты после 7 дней.
# Включайте это только на 1 сервере, если у вас их несколько.
isHead: true